name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          - name: Checkout the main branch
          run: git checkout main  
          - name: Pull latest changes from the main branch
          run: git pull origin main
          - name: Commit changes
          run: |
          git add -A .
          git commit -m "generated" || echo "No changes to commit"
          - name: Push changes
          run: git push origin main
